apiVersion: v2
name: helm-chart-example-ci
version: 1.0.0
description: "Тестовый cm развёрнутый из ci"
type: application
maintainers: 
  - name: FZEN
    email: admin@fzen.pro
    url: https://fzen.pro
appVersion: 1.0.0
dependencies:
  - name: helm-library
    version: ">=0.0.0"
    repository: 'oci://gitlab-registry.gitlab.svc:5000/library/helm/utility/charts'