apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "standard.standardLabels" . | nindent 4 -}}
    {{- include "common.get_dict" (dict "vars" (list .Values.global.labels ) ) | nindent 4 -}}
  {{- include "common.get_dict" (dict "name" "annotations" "vars" (list .Values.global.annotations ) "nindent" 2 ) | nindent 2 }}
data:
  environmentType: "{{ .Values.environmentType }}"
  hostname: "{{ .Values.hostname }}"

 
